# 30-Nov-2015

The bell curve in two dimensions has an analog of standard deviation called **covariance**

In [1]:
import numpy as np
m1 = [2.5, 3.5]
m2 = [0.5, 1]
cov1 = [[1,1],[1,4.5]]
cov2 = [[2,0],[0,1]]

In [3]:
x1 = np.random.multivariate_normal(m1, cov1, 200)
x1

array([[  4.20086652e+00,   6.64413001e+00],
       [  2.88725245e+00,   2.29522957e+00],
       [  3.70826009e+00,   3.81611944e+00],
       [  3.52352730e+00,   4.61962882e+00],
       [  3.74309322e+00,   2.62602288e+00],
       [  1.94662930e+00,   4.41878394e+00],
       [  1.76748288e+00,   3.23369739e+00],
       [  9.40233009e-01,   3.31407881e+00],
       [  3.71230186e+00,   7.46491175e+00],
       [  2.97872216e+00,   2.30500312e+00],
       [  1.46568929e+00,   1.69888586e+00],
       [  2.38623520e+00,   5.82723631e-02],
       [  1.63608657e+00,   2.55751672e+00],
       [  1.66835134e+00,   5.20422555e+00],
       [  1.74960452e+00,   3.60858863e+00],
       [  2.68515917e+00,  -1.41716073e-01],
       [  1.70572234e+00,   5.66280552e+00],
       [  1.54783234e+00,   4.24228239e+00],
       [  1.20292465e+00,   1.86958109e+00],
       [  2.79765801e+00,   9.08905974e-01],
       [  3.71905195e+00,   3.49906640e+00],
       [  1.91348862e+00,   5.34454053e+00],
       [  

In [4]:
x2 = np.random.multivariate_normal(m2, cov2, 300)
x2

array([[  7.43888563e-01,   8.22157269e-01],
       [  1.03391652e+00,   1.65203959e+00],
       [ -6.45816480e-01,  -2.06735053e-01],
       [  7.08798423e-01,   2.11292979e+00],
       [ -1.39088788e+00,   2.09739762e+00],
       [ -4.85539587e-01,   2.52670990e+00],
       [  6.08968518e-01,   5.32716863e-01],
       [  7.12769081e-01,   7.74735152e-02],
       [  3.46134849e-01,   1.82158871e+00],
       [ -2.61934643e+00,   5.61324985e-01],
       [ -2.54161610e-01,   1.84697431e+00],
       [  9.93034388e-01,   9.36839422e-01],
       [  2.08590549e+00,  -1.47587211e+00],
       [ -3.07960891e-01,   4.33489035e-01],
       [ -5.72274700e-01,   5.07180211e-01],
       [ -7.99652960e-01,  -6.72081829e-01],
       [  1.83940263e+00,   1.69504495e-01],
       [  9.45260074e-02,   1.49024518e+00],
       [ -2.02917502e+00,   1.72775239e+00],
       [  2.04463980e-01,   1.29324968e+00],
       [  4.16724610e-01,   8.73910888e-01],
       [ -1.24075290e+00,   1.41122586e+00],
       [ -

In [5]:
import matplotlib.pyplot as plt

In [6]:
plt.plot(x1[:,0],x1[:,1], 'ro')
plt.show()

In [7]:
plt.plot(x2[:,0], x2[:,1], 'bo')
plt.show()

In [8]:
plt.plot(x1[:,0],x1[:,1],'ro',x2[:,0],x2[:,1],'bo')
plt.show()

Example of classifying situation:

* 600 observations in 2 classes, so 600 x 3 matrix (first column is class 1, second column is class 2, and third column is label)
  * 300 of the observations have one label and the other 300 have the other label
  * The training data will be 4/5 of the observations and their labels, so 480 x 3 matrix
    * Randomly shuffle the 600 x 3 matrix and partition into 5 120 x 3 matrices. On average, the labels should be evenly distributed
* Classifier(training, test) --> should return a 120 x 1 matrix of labels
  * Compare this 120 x 1 matrix to the labels of the last 120 observations in the 600 x 3 matrix

**Applying method to our data**

In [9]:
x1.shape

(200, 2)

In [10]:
x2.shape

(300, 2)

In [11]:
# give x1 label "1"
labels1 = np.ones(200).reshape(200,1)
x1_labels = np.hstack((x1, labels1))
x1_labels.shape

(200, 3)

In [14]:
# give x2 label "2"
labels2 = 2 * np.ones(300).reshape(300,1)
x2_labels = np.hstack((x2, labels2))
x2_labels.shape

(300, 3)

In [16]:
# Now stack the two matrices with labels vertically to form a 500 x 3 matrix
data = np.vstack((x1_labels, x2_labels))
data

array([[ 4.20086652,  6.64413001,  1.        ],
       [ 2.88725245,  2.29522957,  1.        ],
       [ 3.70826009,  3.81611944,  1.        ],
       ..., 
       [ 0.11986681,  2.21760055,  2.        ],
       [-1.1146106 ,  2.81901016,  2.        ],
       [-0.31736346,  0.90860631,  2.        ]])

In [18]:
# Now randomly shuffle the data
# Notice that np.random.shuffle() has a side effect
np.random.shuffle(data)
data

# We now have our data (the large matrix of all observations and their labels)

array([[-0.20200661,  0.58518359,  2.        ],
       [ 1.82786061,  2.80087108,  1.        ],
       [-1.2407529 ,  1.41122586,  2.        ],
       ..., 
       [ 0.81999175,  1.04986384,  2.        ],
       [ 0.7270599 ,  0.38853152,  2.        ],
       [-2.61934643,  0.56132498,  2.        ]])

The following demonstrates how to use delete function

In [19]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Axis in numpy arrays: axis=0 is rows and axis=1 is columns

In [21]:
# Killing row 2 of the matrix
# Second argument indicates row/column numbers, third argument is the axis number
np.delete(a, 1, 0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
# Notice that this does not have a side effect
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
# Killing second and third rows
# Notice that multiple elements as an argument must be in tuple form
np.delete(a, (1,2), 0)

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [25]:
# Note that axis specification is optional. Not specifying axis flattens the matrix and the
# element number/numbers indicate element number/numbers in that 1 dimensional matrix
np.delete(a, (1,2))

array([ 0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

As it pertains to the classifying example from earlier:
* Kill the last 100 rows of the data matrix to generate the training matrix
  * You get a 400 x 3 matrix
* Kill the first 400 rows and then the third column of the result to generate test matrix
  * You get a 100 x 2 matrix


## Really useful information

Get this package: **scipy.spatial.distance**
Use this function: **cdist()**
* If you give it two populations, it calculates the distances between each row
  * Will give the distances between every element of training and every element of test
* There are other functions that could simplify work

Check out this function in Numpy: **argsort()**